language: python
python:
  - "3.6"
  - "3.3"
 
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Mock
  - pip install requests
  
# command to run tests
script:
  - pytest
