language: python
python:
  - "3.6"
  - "3.3"
 
# command to install dependencies
install:
  
  - pip install Mock
  - pip install requests
  
  
# command to run tests
script:
  - pip install pytest
  - pytest
